name: Build|Upload|Release Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-pypi:
    if: github.ref == 'refs/heads/main'
    uses: Knuckles-Team/pipelines/.github/workflows/python_pipeline.yml@dad71eff1a14f9de1dc5f6bfb14e093e12cdb2c9 # v2.0.2
    permissions:
      contents: write
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
